---
- hosts: all
  vars_files:
    - vars/{{ env }}.yml
  tasks:
    - name: push dbconn.php
      template:
        src: templates/dbconn.php.j2
        dest: "{{ document_root }}/bitrix/php_interface/dbconn.php"
        backup: yes
    - name: push .settings.php
      template:
        src: templates/settings.php.j2
        dest: "{{ document_root }}/bitrix/.settings.php"
        backup: yes
    - name: push .env
      template:
        src: templates/env.j2
        dest: "{{ document_root }}/local/.env"
        backup: yes
      #when: env != "prod"
    - name: push staging robots.txt
      copy:
        src: files/stage/robots.txt
        dest: "{{ document_root }}/robots.txt"
        backup: yes
      when: env == "stage"
    - name: build assets
      local_action: shell gulp release
      args:
        chdir: ../public/local
    - name: push assets
      synchronize:
        # trailing slash is important, see rsync documentation
        src: ../public/local/templates/main/build/
        dest: "{{ document_root }}/local/templates/main/build"
        delete: yes
      when: env != "dev"
    - name: git-ftp push
      local_action: >
        shell git-ftp push
        {% if ansible_check_mode %}--dry-run{% endif %}
        --user {{ ansible_user }}
        --passwd {{ ansible_ssh_pass }}
        sftp://{{ inventory_hostname }}/{{ repo_path }}
      when: env != "dev"
    - name: clear twig cache
      file:
        state: absent
        path: "{{ document_root }}/bitrix/cache/maximaster/tools.twig"
